apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -rsmc
namespace: minecraft-rsmc
commonLabels: 
  app: minecraft
  edition: rsmc
  env: prod

patches:
  - path: deployment-patch.yaml
