apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -prod
namespace: minecraft-bedrock-prod
commonLabels: 
  app: minecraft
  edition: bedrock
  env: prod

patches:
  - path: deployment-patch.yaml
